/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TMA;
import java.io.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Anas Rahman
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        try{
            txtselect.setModel(m);
            String r,r1,name,bio,result[];
            BufferedReader br = new BufferedReader(new FileReader("TalentRequests.txt"));
            
            while((r=br.readLine())!=null)
            {
                result=r.split("\\|");
                name=result[0];
                bio=result[9];
                str.add(name);
            }
            br.close();
            m.addAll(str);
        }
        catch(IOException e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtselect = new javax.swing.JList<>();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Home");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, -1, -1));

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 100, -1));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENDING REQUESTS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 110, -1, -1));

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 100, -1));

        jButton5.setText("Reset All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, -1));

        jScrollPane1.setViewportView(txtselect);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 240, 300));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anas Rahman\\Documents\\NetBeansProjects\\TalentManagementAgency\\Images\\adminbg.png")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String x=txtselect.getSelectedValue();
        
        String tempname=x;
        String bio;
        String temp,r,res[],name,imgloc;
        int i=txtselect.getSelectedIndex();
        File fp1=new File("HiredTalents.txt");
        try{
            fp1.createNewFile();
            FileWriter fw=new FileWriter(fp1,true);
            BufferedReader br=new BufferedReader(new FileReader("TalentRequests.txt"));
            while((r=br.readLine())!=null){
                res=r.split("\\|");
                name=res[0];
                bio=res[8];
                if(name.compareTo(x)==0){
                    imgloc=res[9];
                    fw.write(x+"|"+bio+"|"+imgloc);                  
                    fw.write("\n");
                }
            }
            br.close();
            fw.flush();
            fw.close();
            
            m.remove(i);
            txtselect.setModel(m);
            
            File tfp=new File("temp.txt");
            File fp=new File("TalentRequests.txt");
            if(!tfp.exists()){
                tfp.createNewFile();
                System.out.println("temp file created");
            }
            BufferedReader br1=new BufferedReader(new FileReader("TalentRequests.txt"));
            FileWriter tfw=new FileWriter(tfp,true);
            String r1,result1[],name1;
            while((r1=br1.readLine())!=null){
                result1=r1.split("\\|");
                name1=result1[0];
                if(!name1.equalsIgnoreCase(tempname)){
                    tfw.write(r1);
                    tfw.write("\n");
                }
            }
            tfw.flush();
            tfw.close();
            br1.close();
            fp.delete();
            tfp.renameTo(fp);
            tfp.delete();
            JOptionPane.showMessageDialog(null, "Application Approved.");
            
        }
        catch(Exception e){

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String tempname=txtselect.getSelectedValue();
        try{
            String r,name,bio,result[];
            int i=txtselect.getSelectedIndex();
            BufferedReader br = new BufferedReader(new FileReader("TalentRequests.txt"));
            if(i!=-1){
                m.remove(i);
            }
            txtselect.setModel(m);
            br.close();
            File tfp=new File("temp.txt");
            File fp=new File("TalentRequests.txt");
            if(!tfp.exists()){
                tfp.createNewFile();
                System.out.println("temp file created");
            }
            BufferedReader br1=new BufferedReader(new FileReader("TalentRequests.txt"));
            FileWriter tfw=new FileWriter(tfp,true);
            String r1,result1[],name1;
            while((r1=br1.readLine())!=null){
                result1=r1.split("\\|");
                name1=result1[0];

                if(!name1.equalsIgnoreCase(tempname)){
                    tfw.write(r1);
                    tfw.write("\n");
                    System.out.println("written "+name1);
                }
            }
            tfw.flush();
            tfw.close();
            br1.close();
            fp.delete();
            tfp.renameTo(fp);
            tfp.delete();
            JOptionPane.showMessageDialog(null, "Application Rejected.");
        }  
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        File fp1=new File("TalentRequests.txt");
        File fp2=new File("History.txt");
        File fp3=new File("HiredTalents.txt");
        fp1.delete();
        fp2.delete();
        fp3.delete();
        JOptionPane.showMessageDialog(null,"Successfully Reset.");
        try{
            fp1.createNewFile();
            fp2.createNewFile();
            fp3.createNewFile();
        }
        catch(Exception e){
            
        }
        this.repaint();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    ArrayList<String> str=new ArrayList<>();
    DefaultListModel m=new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> txtselect;
    // End of variables declaration//GEN-END:variables
}
