/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TMA;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;
import java.awt.event.KeyEvent;

/**
 *
 * @author Anas Rahman
 */
public class ProfileView1 extends javax.swing.JFrame {

    /**
     * Creates new form ProfileView3
     */
    public ProfileView1() {
        initComponents();
        String x=o.j2.get(0).getText();
        setTitle("Profile: "+x);
        txtbio1.setLineWrap(true);
        txtbio1.setWrapStyleWord(true);
        System.out.println(ind);
        try{
            BufferedReader br=new BufferedReader(new FileReader("HiredTalents.txt"));
            while((r=br.readLine())!=null){
                res=r.split("\\|");
                name=res[0];
                if(name.compareTo(x)==0){
                        bio=res[1];
                        imgloc=res[2];
                        txtimg.setIcon(new ImageIcon(imgloc));
                        txtname.setText(x);
                        txtbio1.setText(bio);
                }
            }
        }      
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtimg = new javax.swing.JLabel();
        txtbiopane = new javax.swing.JScrollPane();
        txtbio1 = new javax.swing.JTextArea();
        txtname = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtimg.setOpaque(true);
        jPanel1.add(txtimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 250));

        txtbiopane.setBackground(new java.awt.Color(255, 255, 255));
        txtbiopane.setEnabled(false);
        txtbiopane.setFocusable(false);
        txtbiopane.setOpaque(false);

        txtbio1.setColumns(20);
        txtbio1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txtbio1.setForeground(new java.awt.Color(255, 255, 255));
        txtbio1.setLineWrap(true);
        txtbio1.setRows(5);
        txtbio1.setEnabled(false);
        txtbio1.setOpaque(false);
        txtbiopane.setViewportView(txtbio1);

        jPanel1.add(txtbiopane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 400, 190));

        txtname.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 100, 390, 50));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anas Rahman\\Documents\\NetBeansProjects\\TalentManagementAgency\\Images\\profileviewbg.png")); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
            new Roster().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        // TODO add your handling code here:
        new Roster().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileView1().setVisible(true);
            }
        });
    }
    String r,name,bio,imgloc,res[];
    Roster o=new Roster();
    int ind;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea txtbio1;
    private javax.swing.JScrollPane txtbiopane;
    private javax.swing.JLabel txtimg;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
