/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TMA;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.*;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ImageIcon;
/**
 *
 * @author Anas Rahman
 */
public class Roster extends javax.swing.JFrame {

    /**
     * Creates new form Roster
     */
    public Roster() {
        initComponents();
        int count=0;
        
        j3.add(t1);
        j3.add(t2);
        j3.add(t3);
        j3.add(t4);
        
        j1.add(i1);
        j1.add(i2);
        j1.add(i3);
        j1.add(i4);
        
        j2.add(i1name);
        j2.add(i2name);
        j2.add(i3name);
        j2.add(i4name);
        
        for(int i=0;i<j1.size();i++){
            j1.get(i).setVisible(false);
            j2.get(i).setVisible(false);
            j3.get(i).setVisible(false);
        }
        try{
            String line="";
            String result[];
            File fp=new File("HiredTalents.txt");
            BufferedReader br=new BufferedReader(new FileReader(fp));
            while((line=br.readLine())!=null){
                count++;
                result=line.split("\\|");
                name=result[0];
                bio=result[1];
                imageloc=result[2];
                j1.get(count-1).setVisible(true);
                j1.get(count-1).setIcon(new ImageIcon(imageloc));
                j2.get(count-1).setVisible(true);
                j2.get(count-1).setText(name);
                j3.get(count-1).setVisible(true);
            }
            br.close();  
            check();
        }  
        catch(Exception e)
        {
            
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        i2 = new javax.swing.JLabel();
        i3 = new javax.swing.JLabel();
        i1 = new javax.swing.JLabel();
        i1name = new javax.swing.JLabel();
        i2name = new javax.swing.JLabel();
        i3name = new javax.swing.JLabel();
        i4name = new javax.swing.JLabel();
        i4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roster");
        setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i2MouseClicked(evt);
            }
        });
        jPanel1.add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 200, 200));

        i3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i3MouseClicked(evt);
            }
        });
        jPanel1.add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 200, 200));

        i1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        i1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        i1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                i1MouseEntered(evt);
            }
        });
        jPanel1.add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 200));

        i1name.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        i1name.setForeground(new java.awt.Color(255, 255, 255));
        i1name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i1name.setText("Name 1");
        i1name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        i1name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        i1name.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(i1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, -1));

        i2name.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        i2name.setForeground(new java.awt.Color(255, 255, 255));
        i2name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i2name.setText("Name 1");
        jPanel1.add(i2name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        i3name.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        i3name.setForeground(new java.awt.Color(255, 255, 255));
        i3name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i3name.setText("Name 1");
        jPanel1.add(i3name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 200, -1));

        i4name.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        i4name.setForeground(new java.awt.Color(255, 255, 255));
        i4name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i4name.setText("Name 1");
        jPanel1.add(i4name, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 200, -1));

        i4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        i4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i4MouseClicked(evt);
            }
        });
        jPanel1.add(i4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 200, 200));

        t1.setEnabled(false);
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 280));

        t2.setEnabled(false);
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 220, 280));

        t3.setEnabled(false);
        t3.setFocusable(false);
        t3.setRequestFocusEnabled(false);
        t3.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 220, 280));

        t4.setEnabled(false);
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 220, 280));

        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anas Rahman\\Documents\\NetBeansProjects\\TalentManagementAgency\\Images\\rosterbg.png")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        bg.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void i1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i1MouseEntered
        // TODO addour handling code here:
        
    }//GEN-LAST:event_i1MouseEntered

    private void check(){
        for(int i=0;i<j1.size();i++){
            if(j2.get(i).getText().compareTo("Name 1")==0){
                j2.get(i).setVisible(false);
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void i1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i1MouseClicked
        // TODO add your handling code here:
        new ProfileView1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_i1MouseClicked

    private void i2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i2MouseClicked
        // TODO add your handling code here:
        new ProfileView2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_i2MouseClicked

    private void i3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i3MouseClicked
        // TODO add your handling code here:
        new ProfileView3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_i3MouseClicked

    private void i4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i4MouseClicked
        // TODO add your handling code here:     
        new ProfileView4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_i4MouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        t1.setText("");
        t1.setEditable(false);
        t2.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roster().setVisible(true);
            }
        });
    }
    ArrayList<JLabel> j2=new ArrayList<>();
    ArrayList<JLabel> j1= new ArrayList<>(); 
    ArrayList<JTextField> j3= new ArrayList<>(); 
    
    String bio,name,imageloc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i1name;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i2name;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i3name;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i4name;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
